CREATE TABLE public.waitlist (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NULL,
    email text NOT NULL,
    role text NULL,
    institution text NULL,
    "position" int8 NULL,
    referral_code text NULL,
    referred_by text NULL, -- Add this column for referral tracking
    referral_count int8 DEFAULT 0, -- Add this column to count referrals
    created_at timestamptz NOT NULL DEFAULT now(),
    -- Store feature votes as a JSON object
    feature_votes jsonb DEFAULT '{}',
    CONSTRAINT waitlist_pkey PRIMARY KEY (id),
    CONSTRAINT waitlist_email_key UNIQUE (email)
);

-- Table for storing contact form messages
CREATE TABLE public.contact_messages (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    email text NOT NULL,
    subject text NOT NULL,
    message text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT contact_messages_pkey PRIMARY KEY (id)
);