CREATE TABLE public.waitlist (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NULL,
    email text NOT NULL,
    role text NULL,
    institution text NULL,
    "position" int8 NULL,
    referral_code text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT waitlist_pkey PRIMARY KEY (id),
    CONSTRAINT waitlist_email_key UNIQUE (email)
);
