export interface Emoji {
  char: string;
  name: string;
}

export interface EmojiGroup {
  group: string;
  emojis: Emoji[];
}

export const EMOJI_DATA: EmojiGroup[] = [
  {
    group: "Smileys & Emotion",
    emojis: [
      { char: "😀", name: "grinning face" },
      { char: "😃", name: "grinning face with big eyes" },
      { char: "😄", name: "grinning face with smiling eyes" },
      { char: "😁", name: "beaming face with smiling eyes" },
      { char: "😆", name: "grinning squinting face" },
      { char: "😅", name: "grinning face with sweat" },
      { char: "🤣", name: "rolling on the floor laughing" },
      { char: "😂", name: "face with tears of joy" },
      { char: "🙂", name: "slightly smiling face" },
      { char: "🙃", name: "upside-down face" },
      { char: "😉", name: "winking face" },
      { char: "😊", name: "smiling face with smiling eyes" },
      { char: "😇", name: "smiling face with halo" },
      { char: "🥰", name: "smiling face with hearts" },
      { char: "😍", name: "smiling face with heart-eyes" },
      { char: "🤩", name: "star-struck" },
      { char: "😘", name: "face blowing a kiss" },
      { char: "😗", name: "kissing face" },
      { char: "😚", name: "kissing face with closed eyes" },
      { char: "😙", name: "kissing face with smiling eyes" },
      { char: "😋", name: "face savoring food" },
      { char: "😛", name: "face with tongue" },
      { char: "😜", name: "winking face with tongue" },
      { char: "🤪", name: "zany face" },
      { char: "😝", name: "squinting face with tongue" },
      { char: "🤑", name: "money-mouth face" },
      { char: "🤗", name: "hugging face" },
      { char: "🤭", name: "face with hand over mouth" },
      { char: "🤫", name: "shushing face" },
      { char: "🤔", name: "thinking face" },
      { char: "🤐", name: "zipper-mouth face" },
      { char: "🤨", name: "face with raised eyebrow" },
      { char: "😐", name: "neutral face" },
      { char: "😑", name: "expressionless face" },
      { char: "😶", name: "face without mouth" },
      { char: "😏", name: "smirking face" },
      { char: "😒", name: "unamused face" },
      { char: "🙄", name: "face with rolling eyes" },
      { char: "😬", name: "grimacing face" },
      { char: "🤥", name: "lying face" },
      { char: "😌", name: "relieved face" },
      { char: "😔", name: "pensive face" },
      { char: "😪", name: "sleepy face" },
      { char: "🤤", name: "drool" },
      { char: "😴", name: "sleeping face" },
      { char: "😷", name: "face with medical mask" },
      { char: "🤒", name: "face with thermometer" },
      { char: "🤕", name: "face with head-bandage" },
      { char: "🤢", name: "nauseated face" },
      { char: "🤮", name: "face vomiting" },
      { char: "🤧", name: "sneezing face" },
      { char: "🥵", name: "hot face" },
      { char: "🥶", name: "cold face" },
      { char: "🥴", name: "woozy face" },
      { char: "😵", name: "knocked-out face" },
      { char: "🤯", name: "exploding head" },
      { char: "🤠", name: "cowboy hat face" },
      { char: "🥳", name: "partying face" },
      { char: "😎", name: "smiling face with sunglasses" },
      { char: "🤓", name: "nerd face" },
      { char: "🧐", name: "face with monocle" },
      { char: "😕", name: "confused face" },
      { char: "😟", name: "worried face" },
      { char: "🙁", name: "slightly frowning face" },
      { char: "😮", name: "face with open mouth" },
      { char: "😯", name: "hushed face" },
      { char: "😲", name: "astonished face" },
      { char: "😳", name: "flushed face" },
      { char: "🥺", name: "pleading face" },
      { char: "😦", name: "frowning face with open mouth" },
      { char: "😧", name: "anguished face" },
      { char: "😨", name: "fearful face" },
      { char: "😰", name: "face with open mouth and cold sweat" },
      { char: "😥", name: "sad but relieved face" },
      { char: "😢", name: "crying face" },
      { char: "😭", name: "loudly crying face" },
      { char: "😱", name: "face screaming in fear" },
      { char: "😖", name: "confounded face" },
      { char: "😣", name: "persevering face" },
      { char: "😞", name: "disappointed face" },
      { char: "😓", name: "downcast face with sweat" },
      { char: "😩", name: "weary face" },
      { char: "😫", name: "tired face" },
      { char: "🥱", name: "yawning face" },
      { char: "😤", name: "face with steam from nose" },
      { char: "😡", name: "pouting face" },
      { char: "😠", name: "angry face" },
      { char: "🤬", name: "face with symbols on mouth" },
      { char: "😈", name: "smiling face with horns" },
      { char: "👿", name: "angry face with horns" },
      { char: "💀", name: "skull" },
      { char: "💩", name: "pile of poo" },
      { char: "🤡", name: "clown face" },
      { char: "👹", name: "ogre" },
      { char: "👺", name: "goblin" },
      { char: "👻", name: "ghost" },
      { char: "👽", name: "alien" },
      { char: "👾", name: "alien monster" },
      { char: "🤖", name: "robot" },
      { char: "😺", name: "grinning cat" },
      { char: "😸", name: "grinning cat with smiling eyes" },
      { char: "😹", name: "cat with tears of joy" },
      { char: "😻", name: "smiling cat with heart-eyes" },
      { char: "😼", name: "cat with wry smile" },
      { char: "😽", name: "kissing cat" },
      { char: "🙀", name: "weary cat" },
      { char: "😿", name: "crying cat" },
      { char: "😾", name: "pouting cat" },
      { char: "🙈", name: "see-no-evil monkey" },
      { char: "🙉", name: "hear-no-evil monkey" },
      { char: "🙊", name: "speak-no-evil monkey" },
      { char: "💋", name: "kiss mark" },
      { char: "💌", name: "love letter" },
      { char: "💘", name: "heart with arrow" },
      { char: "💝", name: "heart with ribbon" },
      { char: "💖", name: "sparkling heart" },
      { char: "💗", name: "growing heart" },
      { char: "💓", name: "beating heart" },
      { char: "💞", name: "revolving hearts" },
      { char: "💕", name: "two hearts" },
      { char: "💟", name: "heart decoration" },
      { char: "💔", name: "broken heart" },
      { char: "❤️", name: "red heart" },
      { char: "🧡", name: "orange heart" },
      { char: "💛", name: "yellow heart" },
      { char: "💚", name: "green heart" },
      { char: "💙", name: "blue heart" },
      { char: "💜", name: "purple heart" },
      { char: "🤎", name: "brown heart" },
      { char: "🖤", name: "black heart" },
      { char: "🤍", name: "white heart" },
      { char: "💯", name: "hundred points" },
      { char: "💢", name: "anger symbol" },
      { char: "💥", name: "collision" },
      { char: "💫", name: "dizzy" },
      { char: "💦", name: "sweat droplets" },
      { char: "💨", name: "dash" },
      { char: "🕳", name: "hole" },
      { char: "💣", name: "bomb" },
      { char: "💬", name: "speech balloon" },
      { char: "👁‍🗨", name: "eye in speech bubble" },
      { char: "🗨", name: "left speech bubble" },
      { char: "🗯", name: "right anger bubble" },
      { char: "💭", name: "thought balloon" },
      { char: "💤", name: "zzz" },
    ],
  },
  {
    group: "Animals & Nature",
    emojis: [
      { char: "🐶", name: "dog face" },
      { char: "🐱", name: "cat face" },
      { char: "🐭", name: "mouse face" },
      { char: "🐹", name: "hamster face" },
      { char: "🐰", name: "rabbit face" },
      { char: "🦊", name: "fox face" },
      { char: "🐻", name: "bear face" },
      { char: "🐼", name: "panda face" },
      { char: "🐨", name: "koala" },
      { char: "🐯", name: "tiger face" },
      { char: "🦁", name: "lion face" },
      { char: "🐮", name: "cow face" },
      { char: "🐷", name: "pig face" },
      { char: "🐽", name: "pig nose" },
      { char: "🐸", name: "frog face" },
      { char: "🐵", name: "monkey face" },
      { char: "🐔", name: "chicken" },
      { char: "🐧", name: "penguin" },
      { char: "🐦", name: "bird" },
      { char: "🐤", name: "baby chick" },
      { char: "🐣", name: "hatching chick" },
      { char: "🐥", name: "front-facing baby chick" },
      { char: "🦆", name: "duck" },
      { char: "🦅", name: "eagle" },
      { char: "🦉", name: "owl" },
      { char: "🦇", name: "bat" },
      { char: "🐺", name: "wolf face" },
      { char: "🐗", name: "boar" },
      { char: "🐴", name: "horse face" },
      { char: "🦄", name: "unicorn face" },
      { char: "🐝", name: "honeybee" },
      { char: "🐛", name: "bug" },
      { char: "🦋", name: "butterfly" },
      { char: "🐌", name: "snail" },
      { char: "🐞", name: "lady beetle" },
      { char: "🐜", name: "ant" },
      { char: "🦟", name: "mosquito" },
      { char: "🦗", name: "cricket" },
      { char: "🕷", name: "spider" },
      { char: "🕸", name: "spider web" },
      { char: "🦂", name: "scorpion" },
      { char: "🐢", name: "turtle" },
      { char: "🐍", name: "snake" },
      { char: "🦎", name: "lizard" },
      { char: "🦖", name: "T-Rex" },
      { char: "🦕", name: "sauropod" },
      { char: "🐙", name: "octopus" },
      { char: "🦑", name: "squid" },
      { char: "🦐", name: "shrimp" },
      { char: "🦞", name: "lobster" },
      { char: "🦀", name: "crab" },
      { char: "🐡", name: "blowfish" },
      { char: "🐠", name: "tropical fish" },
      { char: "🐟", name: "fish" },
      { char: "🐬", name: "dolphin" },
      { char: "🐳", name: "spouting whale" },
      { char: "🐋", name: "whale" },
      { char: "🦈", name: "shark" },
      { char: "🐊", name: "crocodile" },
      { char: "🐅", name: "tiger" },
      { char: "🐆", name: "leopard" },
      { char: "🦓", name: "zebra" },
      { char: "🦍", name: "gorilla" },
      { char: "🦧", name: "orangutan" },
      { char: "🐘", name: "elephant" },
      { char: "🦛", name: "hippopotamus" },
      { char: "🦏", name: "rhinoceros" },
      { char: "🐪", name: "camel" },
      { char: "🐫", name: "two-hump camel" },
      { char: "🦒", name: "giraffe" },
      { char: "🦘", name: "kangaroo" },
      { char: "🐃", name: "water buffalo" },
      { char: "🐂", name: "ox" },
      { char: "🐄", name: "cow" },
      { char: "🐎", name: "horse" },
      { char: "🐖", name: "pig" },
      { char: "🐏", name: "ram" },
      { char: "🐑", name: "ewe" },
      { char: "🦙", name: "llama" },
      { char: "🐐", name: "goat" },
      { char: "🦌", name: "deer" },
      { char: "🐕", name: "dog" },
      { char: "🐩", name: "poodle" },
      { char: "🐈", name: "cat" },
      { char: "🐈‍⬛", name: "black cat" },
      { char: "🐓", name: "rooster" },
      { char: "🦃", name: "turkey" },
      { char: "🦚", name: "peacock" },
      { char: "🦜", name: "parrot" },
      { char: "🦢", name: "swan" },
      { char: "🦩", name: "flamingo" },
      { char: "🕊", name: "dove" },
      { char: "🐇", name: "rabbit" },
      { char: "🦝", name: "raccoon" },
      { char: "🦨", name: "skunk" },
      { char: "🦡", name: "badger" },
      { char: "🦦", name: "otter" },
      { char: "🦥", name: "sloth" },
      { char: "🐁", name: "mouse" },
      { char: "🐀", name: "rat" },
      { char: "🐿", name: "chipmunk" },
      { char: "🦔", name: "hedgehog" },
      { char: "🐾", name: "paw prints" },
      { char: "🐉", name: "dragon" },
      { char: "🐲", name: "dragon face" },
      { char: "🌵", name: "cactus" },
      { char: "🎄", name: "Christmas tree" },
      { char: "🌲", name: "evergreen tree" },
      { char: "🌳", name: "deciduous tree" },
      { char: "🌴", name: "palm tree" },
      { char: "🌱", name: "seedling" },
      { char: "🌿", name: "herb" },
      { char: "☘️", name: "shamrock" },
      { char: "🍀", name: "four leaf clover" },
      { char: "🎍", name: "pine decoration" },
      { char: "🎋", name: "tanabata tree" },
      { char: "🍃", name: "leaf fluttering in wind" },
      { char: "🍂", name: "fallen leaf" },
      { char: "🍁", name: "maple leaf" },
      { char: "🍄", name: "mushroom" },
      { char: "🌾", name: "sheaf of rice" },
      { char: "💐", name: "bouquet" },
      { char: "🌷", name: "tulip" },
      { char: "🌹", name: "rose" },
      { char: "🥀", name: "wilted flower" },
      { char: "🌺", name: "hibiscus" },
      { char: "🌸", name: "cherry blossom" },
      { char: "🌼", name: "blossom" },
      { char: "🌻", name: "sunflower" },
      { char: "🌞", name: "sun with face" },
      { char: "🌝", name: "full moon with face" },
      { char: "🌚", name: "new moon with face" },
      { char: "🌕", name: "full moon" },
      { char: "🌙", name: "crescent moon" },
      { char: "🌎", name: "globe showing Americas" },
      { char: "🪐", name: "ringed planet" },
      { char: "💫", name: "dizzy" },
      { char: "⭐️", name: "star" },
      { char: "🌟", name: "glowing star" },
      { char: "✨", name: "sparkles" },
      { char: "⚡️", name: "high voltage" },
      { char: "☄️", name: "comet" },
      { char: "💥", name: "collision" },
      { char: "🔥", name: "fire" },
      { char: "🌪", name: "tornado" },
      { char: "🌈", name: "rainbow" },
      { char: "☀️", name: "sun" },
      { char: "☁️", name: "cloud" },
      { char: "🌧", name: "cloud with rain" },
      { char: "⛈", name: "cloud with lightning and rain" },
      { char: "❄️", name: "snowflake" },
      { char: "☃️", name: "snowman" },
      { char: "🌬", name: "wind face" },
      { char: "💨", name: "dash" },
      { char: "💧", name: "droplet" },
      { char: "💦", name: "sweat droplets" },
      { char: "🌊", name: "water wave" },
    ],
  },
  {
    group: "Food & Drink",
    emojis: [
      { char: "🍏", name: "green apple" },
      { char: "🍎", name: "red apple" },
      { char: "🍐", name: "pear" },
      { char: "🍊", name: "tangerine" },
      { char: "🍋", name: "lemon" },
      { char: "🍌", name: "banana" },
      { char: "🍉", name: "watermelon" },
      { char: "🍇", name: "grapes" },
      { char: "🍓", name: "strawberry" },
      { char: "🫐", name: "blueberries" },
      { char: "🍈", name: "melon" },
      { char: "🍒", name: "cherries" },
      { char: "🍑", name: "peach" },
      { char: "🥭", name: "mango" },
      { char: "🍍", name: "pineapple" },
      { char: "🥥", name: "coconut" },
      { char: "🥝", name: "kiwi fruit" },
      { char: "🍅", name: "tomato" },
      { char: "🍆", name: "eggplant" },
      { char: "🥑", name: "avocado" },
      { char: "🥦", name: "broccoli" },
      { char: "🥒", name: "cucumber" },
      { char: "🌶", name: "hot pepper" },
      { char: "🌽", name: "ear of corn" },
      { char: "🥕", name: "carrot" },
      { char: "🫒", name: "olive" },
      { char: "🧄", name: "garlic" },
      { char: "🧅", name: "onion" },
      { char: "🥔", name: "potato" },
      { char: "🍠", name: "roasted sweet potato" },
      { char: "🥐", name: "croissant" },
      { char: "🥯", name: "bagel" },
      { char: "🍞", name: "bread" },
      { char: "🥖", name: "baguette bread" },
      { char: "🥨", name: "pretzel" },
      { char: "🧀", name: "cheese wedge" },
      { char: "🥚", name: "egg" },
      { char: "🍳", name: "cooking" },
      { char: "🧈", name: "butter" },
      { char: "🥞", name: "pancakes" },
      { char: "🧇", name: "waffle" },
      { char: "🥓", name: "bacon" },
      { char: "🥩", name: "cut of meat" },
      { char: "🍗", name: "poultry leg" },
      { char: "🍖", name: "meat on bone" },
      { char: "🌭", name: "hot dog" },
      { char: "🍔", name: "hamburger" },
      { char: "🍟", name: "french fries" },
      { char: "🍕", name: "pizza" },
      { char: "🥪", name: "sandwich" },
      { char: "🌮", name: "taco" },
      { char: "🌯", name: "burrito" },
      { char: "🥗", name: "green salad" },
      { char: "🥘", name: "shallow pan of food" },
      { char: "🍜", name: "steaming bowl" },
      { char: "🍝", name: "spaghetti" },
      { char: "🍣", name: "sushi" },
      { char: "🍤", name: "fried shrimp" },
      { char: "🍙", name: "rice ball" },
      { char: "🍚", name: "cooked rice" },
      { char: "🍘", name: "rice cracker" },
      { char: "🍢", name: "oden" },
      { char: "🍡", name: "dango" },
      { char: "🍧", name: "shaved ice" },
      { char: "🍨", name: "ice cream" },
      { char: "🍦", name: "soft serve" },
      { char: "🥧", name: "pie" },
      { char: "🧁", name: "cupcake" },
      { char: "🍰", name: "shortcake" },
      { char: "🎂", name: "birthday cake" },
      { char: "🍮", name: "custard" },
      { char: "🍭", name: "lollipop" },
      { char: "🍬", name: "candy" },
      { char: "🍫", name: "chocolate bar" },
      { char: "🍿", name: "popcorn" },
      { char: "🍩", name: "doughnut" },
      { char: "🍪", name: "cookie" },
      { char: "🌰", name: "chestnut" },
      { char: "🥜", name: "peanuts" },
      { char: "🍯", name: "honey pot" },
      { char: "🥛", name: "glass of milk" },
      { char: "🍼", name: "baby bottle" },
      { char: "☕️", name: "hot beverage" },
      { char: "🍵", name: "teacup without handle" },
      { char: "🧃", name: "beverage box" },
      { char: "🥤", name: "cup with straw" },
      { char: "🍶", name: "sake" },
      { char: "🍺", name: "beer mug" },
      { char: "🍻", name: "clinking beer mugs" },
      { char: "🥂", name: "clinking glasses" },
      { char: "🍷", name: "wine glass" },
      { char: "🥃", name: "tumbler glass" },
      { char: "🍸", name: "cocktail glass" },
      { char: "🍹", name: "tropical drink" },
      { char: "🍾", name: "bottle with popping cork" },
      { char: "🧊", name: "ice" },
      { char: "🥄", name: "spoon" },
      { char: "🍴", name: "fork and knife" },
      { char: "🍽", name: "fork and knife with plate" },
      { char: "🥣", name: "bowl with spoon" },
      { char: "🧂", name: "salt" },
    ],
  },
  {
      group: "Activities",
      emojis: [
          { char: "⚽️", name: "soccer ball" },
          { char: "🏀", name: "basketball" },
          { char: "🏈", name: "american football" },
          { char: "⚾️", name: "baseball" },
          { char: "🥎", name: "softball" },
          { char: "🎾", name: "tennis" },
          { char: "🏐", name: "volleyball" },
          { char: "🏉", name: "rugby football" },
          { char: "🎱", name: "pool 8 ball" },
          { char: "🏓", name: "ping pong" },
          { char: "🏸", name: "badminton" },
          { char: "🏒", name: "ice hockey" },
          { char: "🏑", name: "field hockey" },
          { char: "🏏", name: "cricket game" },
          { char: "🎯", name: "bullseye" },
          { char: "⛳️", name: "flag in hole" },
          { char: "🪁", name: "kite" },
          { char: "🏹", name: "bow and arrow" },
          { char: "🎣", name: "fishing pole" },
          { char: "🥊", name: "boxing glove" },
          { char: "🥋", name: "martial arts uniform" },
          { char: "⛸", name: "ice skate" },
          { char: "🎿", name: "skis" },
          { char: "⛷", name: "skier" },
          { char: "🏂", name: "snowboarder" },
          { char: "🏋️‍♀️", name: "woman lifting weights" },
          { char: "🏋️‍♂️", name: "man lifting weights" },
          { char: "🚴‍♀️", name: "woman biking" },
          { char: "🚴‍♂️", name: "man biking" },
          { char: "🏆", name: "trophy" },
          { char: "🥇", name: "1st place medal" },
          { char: "🥈", name: "2nd place medal" },
          { char: "🥉", name: "3rd place medal" },
          { char: "🎖", name: "military medal" },
          { char: "🎫", name: "ticket" },
          { char: "🎟", name: "admission tickets" },
          { char: "🎭", name: "performing arts" },
          { char: "🎨", name: "artist palette" },
          { char: "🎬", name: "clapper board" },
          { char: "🎤", name: "microphone" },
          { char: "🎧", name: "headphone" },
          { char: "🎼", name: "musical score" },
          { char: "🎹", name: "musical keyboard" },
          { char: "🥁", name: "drum" },
          { char: "🎸", name: "guitar" },
          { char: "🎻", name: "violin" },
          { char: "🎲", name: "game die" },
          { char: "🧩", name: "puzzle piece" },
          { char: "🎮", name: "video game" },
          { char: "👾", name: "alien monster" },
      ]
  }
];
