import React from "react";
import {
  SearchCheck,
  Shield,
  BookOpen,
  AlertCircle,
  ArrowRight,
  Database,
  FileCheck,
  CheckCircle2,
  ExternalLink,
} from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "../../components/ui/button";
import Layout from "../../components/Layout";
import { Helmet } from "react-helmet-async";

const CitationVerificationSEO: React.FC = () => {
  return (
    <Layout>
      <Helmet>
        <title>How to Verify Citation Credibility | ColabWize</title>
        <meta
          name="description"
          content="Master the art of citation auditing. Learn how to verify research claims, avoid hallucinated sources, and ensure your academic work is irrefutable."
        />
      </Helmet>

      <div className="bg-white min-h-screen">
        {/* Header */}
        <header className="py-20 border-b border-gray-100 bg-slate-50">
          <div className="container-custom max-w-4xl mx-auto">
            <div className="flex items-center gap-2 mb-6">
              <Link
                to="/academic-integrity"
                className="text-blue-600 font-bold text-sm hover:underline flex items-center gap-1">
                <Shield className="w-4 h-4" /> Academic Integrity Hub
              </Link>
              <span className="text-gray-300">/</span>
              <span className="text-gray-500 text-sm">Expert Guides</span>
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-extrabold text-gray-900 mb-8 tracking-tight leading-tight">
              The Researcher's Guide to{" "}
              <span className="text-green-600">Citation Verification</span>
            </h1>
            <p className="text-xl text-gray-600 leading-relaxed mb-10">
              In an era of AI hallucination, "vouching" for your sources is the
              ultimate mark of quality. Learn how to audit every claim and
              verify the credibility of your bibliography.
            </p>
            <div className="flex gap-4">
              <div className="px-4 py-2 bg-green-100 text-green-700 rounded-lg text-sm font-bold flex items-center gap-2">
                <Database className="w-4 h-4" /> Verified Against 200M+ Records
              </div>
            </div>
          </div>
        </header>

        {/* Content */}
        <article className="py-20 container-custom max-w-4xl mx-auto">
          <div className="prose prose-green max-w-none prose-lg font-secondary">
            <h2 className="text-3xl font-bold text-gray-900 mb-6 font-primary">
              The Danger of "Hallucinated" Research
            </h2>
            <p>
              Generative AI is a powerful tool, but it frequently creates
              plausible-sounding citations for papers that do not exist. For a
              student or researcher, submitting a document with a single fake
              citation can lead to immediate expulsion or academic disgrace.
            </p>

            <div className="my-12 p-8 bg-red-50 rounded-3xl border border-red-100 flex gap-6">
              <div className="shrink-0">
                <AlertCircle className="w-10 h-10 text-red-600" />
              </div>
              <div>
                <h4 className="text-red-900 font-bold mb-2">
                  The Hallucination Risk
                </h4>
                <p className="text-red-800 mb-0">
                  70% of researchers reported encountering at least one fake
                  citation generated by an LLM in the last year. Manual
                  verification is slow, but automated auditing is now a
                  necessity.
                </p>
              </div>
            </div>

            <h2 className="text-3xl font-bold text-gray-900 mt-16 mb-6 font-primary">
              How to Audit Your Citations
            </h2>

            <section className="space-y-12 my-12">
              <div className="bg-white p-8 rounded-3xl border border-gray-100 shadow-sm border-l-4 border-l-green-500">
                <h3 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <FileCheck className="text-green-600" /> 1. Cross-Reference
                  with DOI & ISSN
                </h3>
                <p className="text-gray-600">
                  Every legitimate academic publication has a Digital Object
                  Identifier (DOI). If your source lacks a verifiable DOI that
                  links back to a known publisher (like Elsevier, Springer, or
                  Wiley), it is a major red flag.
                </p>
              </div>

              <div className="bg-white p-8 rounded-3xl border border-gray-100 shadow-sm border-l-4 border-l-green-500">
                <h3 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <SearchCheck className="text-green-600" /> 2. Verify
                  Contextual Accuracy
                </h3>
                <p className="text-gray-600">
                  It's not enough for the paper to exist. Does the paper
                  actually *say* what you claim it says? Modern auditing tools
                  compare the semantic context of your claim against the
                  abstract and findings of the source material.
                </p>
              </div>

              <div className="bg-white p-8 rounded-3xl border border-gray-100 shadow-sm border-l-4 border-l-green-500">
                <h3 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <Database className="text-green-600" /> 3. Use an Automated
                  Auditor
                </h3>
                <p className="text-gray-600">
                  ColabWize's **Citation Verification System** scans your entire
                  document in seconds, flagging missing DOIs, inactive links,
                  and claims that don't match the source abstracts.
                </p>
              </div>
            </section>

            <div className="my-20 text-center">
              <h3 className="text-2xl font-bold text-gray-900 mb-6 font-primary">
                Stop Guessing. Start Verifying.
              </h3>
              <p className="text-gray-600 mb-10 max-w-2xl mx-auto">
                ColabWize connects your editor directly to the world's leading
                research databases, ensuring your bibliography is as strong as
                your arguments.
              </p>
              <div className="flex justify-center gap-4">
                <Button
                  asChild
                  className="bg-green-600 hover:bg-green-700 font-bold px-10 h-14 min-w-[200px]">
                  <Link to="/signup">Verify Your Citations</Link>
                </Button>
                <Button
                  asChild
                  className="border-gray-200 text-gray-700 hover:bg-gray-50 font-bold px-10 h-14 min-w-[200px]">
                  <Link to="/how-to-check-citation-credibility">
                    Read the Student Guide
                  </Link>
                </Button>
              </div>
            </div>
          </div>
        </article>

        {/* Supporting Section */}
        <section className="py-20 bg-slate-50">
          <div className="container-custom max-w-5xl mx-auto">
            <h4 className="text-lg font-bold text-gray-900 mb-12 uppercase tracking-widest text-center">
              Why Source Credibility Matters
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              <div className="text-center">
                <div className="w-16 h-16 bg-white rounded-2xl shadow-sm flex items-center justify-center mx-auto mb-6">
                  <CheckCircle2 className="w-8 h-8 text-green-500" />
                </div>
                <h5 className="font-bold mb-2">Peer Review Proof</h5>
                <p className="text-sm text-gray-500">
                  Ensure your work stands up to the most rigorous peer review
                  standards by using only verified sources.
                </p>
              </div>
              <div className="text-center">
                <div className="w-16 h-16 bg-white rounded-2xl shadow-sm flex items-center justify-center mx-auto mb-6">
                  <ExternalLink className="w-8 h-8 text-green-500" />
                </div>
                <h5 className="font-bold mb-2">Impact Tracking</h5>
                <p className="text-sm text-gray-500">
                  Connect with highly cited research that increases the
                  visibility and impact of your own findings.
                </p>
              </div>
              <div className="text-center">
                <div className="w-16 h-16 bg-white rounded-2xl shadow-sm flex items-center justify-center mx-auto mb-6">
                  <BookOpen className="w-8 h-8 text-green-500" />
                </div>
                <h5 className="font-bold mb-2">Avoid Retractions</h5>
                <p className="text-sm text-gray-500">
                  Prevent future retractions by catching invalid or outdated
                  references before publication.
                </p>
              </div>
            </div>
          </div>
        </section>
      </div>
    </Layout>
  );
};

export default CitationVerificationSEO;
