import React from "react";
import { History, Shield, Lock, ArrowRight, Clock, Zap } from "lucide-react";
import { Link } from "react-router-dom";
import Layout from "../../../components/Layout";
import { Helmet } from "react-helmet-async";

const WhatIsAuthorshipVerification: React.FC = () => {
    return (
        <Layout>
            <Helmet>
                <title>What is Authorship Verification? | Academic Defensibility | ColabWize</title>
                <meta
                    name="description"
                    content="Define authorship verification in research and writing. Learn how students prove their work is human-written and original in the age of AI."
                />
            </Helmet>

            <div className="bg-white min-h-screen">
                <article className="py-20 container-custom max-w-3xl mx-auto">
                    <div className="flex items-center gap-2 mb-8 uppercase tracking-widest text-xs font-bold text-blue-600">
                        <Lock className="w-4 h-4" /> Academic Definitions
                    </div>
                    <h1 className="text-4xl md:text-5xl font-extrabold text-gray-900 mb-8 tracking-tight">
                        What is Authorship Verification?
                    </h1>

                    <div className="prose prose-lg prose-slate max-w-none font-primary">
                        <p className="text-xl text-gray-700 leading-relaxed bg-slate-50 p-8 rounded-3xl border border-slate-100 italic">
                            "Authorship verification is the process of confirming that a specific creative work—often
                            academic text—was indeed authored by the person who claims to have written it, as
                            opposed to being generated by AI or sourced through contract cheating."
                        </p>

                        <h2 className="text-2xl font-bold mt-12 mb-4">Keys to Authorship Verification</h2>
                        <p>
                            Unlike traditional plagiarism detection, authorship verification looks at the **creation process**:
                        </p>
                        <ul className="space-y-4">
                            <li className="flex gap-4 p-4 rounded-xl border border-gray-100 shadow-sm transition-shadow hover:shadow-md">
                                <History className="w-6 h-6 text-blue-600 shrink-0" />
                                <div>
                                    <h4 className="font-bold">Temporal Logs</h4>
                                    <p className="text-sm text-gray-500">Checking the time spent and the progression of the draft over multiple sessions.</p>
                                </div>
                            </li>
                            <li className="flex gap-4 p-4 rounded-xl border border-gray-100 shadow-sm transition-shadow hover:shadow-md">
                                <Zap className="w-6 h-6 text-blue-600 shrink-0" />
                                <div>
                                    <h4 className="font-bold">Keystroke Dynamics</h4>
                                    <p className="text-sm text-gray-500">The unique pattern of typing, including pause times and correction cycles, which is as distinct as a signature.</p>
                                </div>
                            </li>
                            <li className="flex gap-4 p-4 rounded-xl border border-gray-100 shadow-sm transition-shadow hover:shadow-md">
                                <Clock className="w-6 h-6 text-blue-600 shrink-0" />
                                <div>
                                    <h4 className="font-bold">Revision Granularity</h4>
                                    <p className="text-sm text-gray-500">A human-written paper has a messy history of deletions, rephrasing, and formatting changes that AI cannot simulate.</p>
                                </div>
                            </li>
                        </ul>

                        <h2 className="text-2xl font-bold mt-12 mb-4 font-primary">Academic Importance</h2>
                        <p>
                            As generative AI becomes more sophisticated, Universities are moving away from simple software scores.
                            **Authorship Verification** has become the primary method for students to provide "Academic Defensibility"—the
                            ability to prove their intellectual ownership of a document in the event of an accusation.
                        </p>

                        <div className="mt-16 p-8 bg-blue-600 rounded-3xl text-white shadow-2xl">
                            <h3 className="text-xl font-bold mb-4 text-white">Prove Your Originality</h3>
                            <p className="text-blue-100 mb-8">
                                With ColabWize, you can generate a verifiable authorship trail for every assignment.
                                Protect your career and your reputation with the industry's most advanced verification logs.
                            </p>
                            <Link to="/signup" className="inline-flex items-center font-bold text-white hover:underline">
                                Explore the Authorship System <ArrowRight className="ml-2 w-4 h-4" />
                            </Link>
                        </div>
                    </div>
                </article>
            </div>
        </Layout>
    );
};

export default WhatIsAuthorshipVerification;
